"""Small field-line utilities for Poisson/electrostatic bridge experiments.

These routines are intentionally simple. They are meant for low-dimensional toy
experiments and for making the field-line bridge idea concrete, not for training
large PFGM-style models.
"""

from __future__ import annotations

from typing import Callable

import numpy as np
from numpy.typing import NDArray

Array = NDArray[np.float64]
FieldFn = Callable[[Array], Array]


def softened_coulomb_field(
    query: Array,
    charges: Array,
    weights: Array | None = None,
    softening: float = 1e-3,
) -> Array:
    """Evaluate a softened inverse-power Coulomb-like field.

    In ``m`` ambient dimensions, the unsoftened field generated by point charges
    scales like ``(y-c)/||y-c||^m``. We use a softened denominator for numerical
    stability.
    """
    query = np.asarray(query, dtype=np.float64)
    charges = np.asarray(charges, dtype=np.float64)
    if query.ndim != 2 or charges.ndim != 2:
        raise ValueError("query and charges must have shape (n, m) and (k, m)")
    if query.shape[1] != charges.shape[1]:
        raise ValueError("query and charges must have the same ambient dimension")
    if softening <= 0:
        raise ValueError("softening must be positive")

    if weights is None:
        weights = np.ones(charges.shape[0], dtype=np.float64) / max(charges.shape[0], 1)
    weights = np.asarray(weights, dtype=np.float64)
    if weights.shape != (charges.shape[0],):
        raise ValueError("weights must have shape (num_charges,)")

    diff = query[:, None, :] - charges[None, :, :]
    r2 = np.sum(diff**2, axis=-1) + softening**2
    ambient_dim = query.shape[1]
    denom = r2 ** (ambient_dim / 2.0)
    return np.sum(weights[None, :, None] * diff / denom[:, :, None], axis=1)


def integrate_field_lines(
    y0: Array,
    field_fn: FieldFn,
    step_size: float = 1e-2,
    n_steps: int = 1000,
    direction: float = -1.0,
    normalize: bool = True,
) -> Array:
    """Euler-integrate field lines from initial states.

    Returns an array of shape ``(n_steps + 1, n, dim)``.
    """
    y = np.asarray(y0, dtype=np.float64)
    if y.ndim != 2:
        raise ValueError("y0 must have shape (n, dim)")
    if step_size <= 0:
        raise ValueError("step_size must be positive")
    if n_steps <= 0:
        raise ValueError("n_steps must be positive")

    path = np.empty((n_steps + 1, *y.shape), dtype=np.float64)
    path[0] = y
    current = y.copy()
    for i in range(1, n_steps + 1):
        field = np.asarray(field_fn(current), dtype=np.float64)
        if field.shape != current.shape:
            raise ValueError("field_fn must return an array with the same shape as its input")
        if normalize:
            norm = np.linalg.norm(field, axis=1, keepdims=True)
            field = field / np.maximum(norm, 1e-12)
        current = current + float(direction) * step_size * field
        path[i] = current
    return path
